# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 10:31
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
